### ISSUE TITLE
Cannot dynamically update table contents   

### ISSUE THREAD

**Issue by laterdayi** [rickypid/flutter_expandable_table#34] opened 2024-05-29 14:37 UTC
Cannot dynamically update table contents

```
ExpandableTableCell _buildCell(String content, {CellBuilder? builder}) {
    return ExpandableTableCell(
      child: builder != null
          ? null
          : GestureDetector(
              onTap: () {
                print('Cell $content tapped');
                // update cell content
                setState(() {
                  data['rows'][0]['columns'][0]['value'] = 'Updated';
                });
              },
              child: DefaultCellCard(
                child: Center(
                  child: Text(
                    content,
                    style: textStyle,
                  ),
                ),
              ),
            ),
      builder: builder,
    );
  }
```

**Comment by wajipu** [comment] 2024-11-06 02:52
How can you update it

**Comment by rickypid** [comment] 2024-11-17 09:03
Duplicate of #15

**Closed by rickypid** 2024-11-17 09:03 UTC
Labels: question
